### ISSUE TITLE
Longer analysis time for WES

### ISSUE THREAD

**Issue by CirclesYuan** [nygenome/Conpair#22]

**Comment by CirclesYuan** [comment]
Multiple threads supporting feasible? BTW, GATK4 Pileup may output line without 7 columns, which may causes an error corresping as follows.

Traceback (most recent call last):
  File "/path/to/Conpair/scripts/estimate_tumor_normal_contamination.py", line 96, in <module>
    pileup = ContaminationMarker.parse_mpileup_line(line, min_map_quality=MMQ)
  File "/path/to/Conpair//modules/ContaminationMarker.py", line 71, in parse_mpileup_line
    baseQs = baseQ2int(line[4])
IndexError: list index out of range
