### ISSUE TITLE
estimate_tumor_normal_contamination.py: ValueError: Not a bracketing interval.

### ISSUE THREAD

**Issue by iranmdl** [nygenome/Conpair#3]
Hello,
I'm having the following error when trying to estimate the contamination in my samples:
This is my **command**:

```
/shared/tools/src/Conpair/.env/bin/python /shared/tools/src/Conpair/scripts/estimate_tumor_normal_contamination.py  -T tumor.pileup -N normal.pileup -Q 1
Normal sample contamination level: 2.774%

```

And this is the **error**:
```
Traceback (most recent call last):
  File "/shared/tools/src/Conpair/scripts/estimate_tumor_normal_contamination.py", line 215, in <module>
    optimal_val = ContaminationModel.apply_brents_algorithm(Data, Scores, (x1, x2, x3))
  File "/shared/tools/src/Conpair/modules/ContaminationModel.py", line 114, in apply_brents_algorithm
    optimal_val = scipy.optimize.brent(f, brack=(x1, x2, x3), tol=1.0e-07, maxiter=30)
  File "/shared/tools/src/Conpair/.env/local/lib/python2.7/site-packages/scipy/optimize/optimize.py", line 2003, in brent
    res = _minimize_scalar_brent(func, brack, args, **options)
  File "/shared/tools/src/Conpair/.env/local/lib/python2.7/site-packages/scipy/optimize/optimize.py", line 2035, in _minimize_scalar_brent
    brent.optimize()
  File "/shared/tools/src/Conpair/.env/local/lib/python2.7/site-packages/scipy/optimize/optimize.py", line 1841, in optimize
    xa, xb, xc, fa, fb, fc, funcalls = self.get_bracket_info()
  File "/shared/tools/src/Conpair/.env/local/lib/python2.7/site-packages/scipy/optimize/optimize.py", line 1829, in get_bracket_info
    raise ValueError("Not a bracketing interval.")
ValueError: Not a bracketing interval.
```

**Comment by ewabergmann** [comment]
Hi iranmdl,

I apologize for a very late response (I am currently on maternity leave).
If you are still interested in solving the issue, would you mind sharing the tumor and normal pileup files?

Thank you for reporting the issue!
