### ISSUE TITLE
Markers for GRCH38

### ISSUE THREAD

**Issue by Kinga277** [nygenome/Conpair#8]
Hello. Where can I get or How I can create the markers for the genome GRCh38 ?

**Comment by ewabergmann** [comment]
Hi Kinga, I have added the marker files compatible with GRCh38. They have been created by my colleagues from the New York Genome Center by lifting over the original markers.

**Comment by kw10** [comment]
I've tried using the GRCh38 liftOver file you provided. I am able to produce pileupe files but when I run verify_concordance.py (and estimate_tumour_normal_contamination.py) I get this error:

```
Traceback (most recent call last):

  File "/software/CASM/modules/installs/conpair/conpair-0.2/scripts/verify_concordance.py", line 55, in <module>
    Markers = get_markers(MARKER_FILE)

  File "/software/CASM/modules/installs/conpair/conpair-0.2/modules/ContaminationMarker.py", line 44, in get_markers

    M = Marker(line[0], line[1], line[2], line[3], float(line[4]))
IndexError: list index out of range
```

If I don't specify a marker file, I assume it is using the default GRCh37 file because I get this message:
```
WARNING: There are no shared markers between the tumor and the normal samples that meet the specified coverage requirements (1)
Is the coverage of your samples high enough?
Exiting...
```
How should I be running verify_concordance.py with GRCh38?

Thanks
Kikm
